import React, { useEffect, useState} from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { getCookie } from 'cookies-next';
import MyCarousel from './api/Components/carousel.js'
import Content from './api/Components/content.js'
import Sidebar from './api/Components/SideBar.js'
import Box from '@mui/material/Box';
import Container from '@mui/material/Container';
import Grid from '@mui/material/Grid';
import axios from 'axios'
import Snackbar from '@mui/material/Snackbar';
import MuiAlert from '@mui/material/Alert';

const Alert = React.forwardRef(function Alert(props, ref) {
  return <MuiAlert elevation={6} ref={ref} variant="filled" {...props} />;
});


export default function Home() {

  const [error, setError] = useState("");
  const [created, setCreated] = useState(false);
  const [creating , setCreating] = useState(false);
  const [items, setItems] = useState()
  const [cookie, setCookie] = useState("")

  axios.defaults.headers.post['Access-Control-Allow-Origin'] = '*';

   const handleClose = (event, reason) => {
    if (reason === 'clickaway') {
      return;
    }

    setCreated(false);
  };

  const addGood = (url, params) => {
    setCreating(true);
    axios.post(url, params).then(function (res){
      if(res.data){
        console.log(res.data)

        setCreated(true)
        setCreating(false)

      }
    }).catch((error) => { 
     setError(error.message)
      setCreating(false)
      })
  }

  const getGoods = (url, params) => {
    axios.post(url, params).then((res) =>{
      //setItems(res.data)
      console.log(res.data)
    }).catch((error) => {
      console.log(error.message)
    })
  }
  const removeGood = (url, params) => {
    axios.post(url, params).then((res) => {
      console.log(res.data)
    }).catch((error) => {
      console.log(error.message)
    })
  }
  const getJson = (url) => {
    axios.get(url).then((res) => {
      if(res.data){
        setItems(res.data)
      }
    }).catch((error) =>{
      setError(error.message)
    })
  }

  const cook = getCookie("SID")
  console.log(cook)
  useEffect(() =>{
    getJson("https://jsonplaceholder.typicode.com/photos")
    getGoods("/api/cart/list", { lang : "1", shop : "1" }, { headers :{Authorization: `Bearer ${cook}` }})
  },[])

  return (
    <div className={styles.app}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container style={{ paddingTop : "30px" }} fluid>
        <Grid container spacing={2}>
          <Grid item xs={5}>
            <Sidebar addGood={addGood} creating={creating} error={error} />
          </Grid>
          <Grid item xs={7}>
             {items  ? <MyCarousel items={items}/> : <div></div> }
          </Grid>
          <Grid item xs={5}></Grid>
          <Grid item xs={7}>
             <Content removeGood={removeGood}/>
          </Grid>
        </Grid>
         <Snackbar open={created} autoHideDuration={6000} onClose={handleClose}>
        <Alert onClose={handleClose} severity="success" sx={{ width: '100%' }}>
          Товар был добавлен
        </Alert>
      </Snackbar>
      </Container>
    </div>
  )
}
